numpy array is similar to python list but it has some advantages:
1.) requires less memory
2.) fast to implement 
3.) it is easy/convinient to use 

very useful for n-dimensional array object 

In [ ]:
# creating a numpy array

import numpy as np 
a=np.array([1,1,2,2,3,3,4])
a


array([1, 1, 2, 2, 3, 3, 4])

In [ ]:
a[0]


1

In [ ]:

a[3]


2

In [ ]:
a[5]

3

In [ ]:
a[6]

4

** sys.getsizeof(5) is taking the value of size of each element of a list while
** len(l)  is the total length of the list

array.size is the total length of the array
** and note that 
arange() is similar to the range

In [ ]:
# LESS Memory  requirement of numpy
import numpy as np
import time
import sys

L=range(1000)
print(sys.getsizeof(5)*len(L))

array=np.arange(1000)
print(array.size*array.itemsize)

28000
8000


here in above examople the size of one list element is 28 bytes while that of the numpy array is 8 bytes this is because in list firstly it stores the pointer for every values then store the values in the corresponding address

In [ ]:
# numpy array is fast and convinient

import numpy as np
import time
import sys

size=1111111
l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)

start_time=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("time taken by python list to compute is: ",(time.time()-start_time)*1000)

start=time.time()
result=a1+a2
print("numpy array took :",(time.time()-start)*1000)


time taken by python list to compute is:  382.80248641967773
numpy array took : 28.59640121459961


convinient to use


In [ ]:
a1=np.array([1,2,3])
a2=np.array([4,6,9])
a1+a2

array([ 5,  8, 12])

In [ ]:
a1*a2

array([ 4, 12, 27])

In [ ]:
a2-a1

array([3, 4, 6])

In [ ]:
a2/a1

array([4., 3., 3.])