**Creating a 2 dimensional array**

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a


array([[1, 2],
       [3, 4],
       [5, 6]])

**Using  "ndim" method
 to get the dimension of the array**

In [ ]:
a=np.array([1,2,3,4])
a.ndim

1

In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [ ]:
a=np.array([[[1,2,3],[4,5,6],[7,7,8]]])
a.ndim

3

**using  ''itemsize'' method to get the size of the item/element of a array**

In [ ]:
a=np.array([1,2,3,4])
a.itemsize      # here 8 byte is the size of int datatype

dtype('int64')

**using "dtype" method to get the datatype of the elements**

In [ ]:
a=np.array([1,2,3,4])
a.dtype

dtype('int64')

**creating a numpy array with its value of float datatype**

In [ ]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
print(a.itemsize)
a

8


array([[1., 2.],
       [3., 4.],
       [5., 6.]])

**using "size" method to get the size of the array(i.e to get the total no of elements in the numpy array)**


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a.size

6

**using "shape" method to get the no of rows and no of columms**

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6],[7,9]],dtype=np.float64)
a.shape

(4, 2)

**creating a numpy array with complex values using dtype=np.complex while declaration**

In [ ]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.complex)
print(a.itemsize)
a

16


<ipython-input-6-563b64934849>:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array([[1,2],[3,4],[5,6]],dtype=np.complex)


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

**using "zero()" method to intialize a numpy array with all its elements equal to zero**

In [ ]:
# created a 4(no of rows) by 3(no of columns) array with all elements equal to zero
import numpy as np 
a=np.zeros((4,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**using "ones" method to intilize a array with all its elements equal to one**

In [ ]:
# created a 5(no of rows) by 4(no of columns) array with all elements equal to one
import numpy as np
a=np.ones((5,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Range method**

In [ ]:
l=range(7)
print(l)
print(l[0])
print(l[1])
print(l[6])
print(l[4])
print(l[5])

range(0, 7)
0
1
6
4
5


**Arange method in numpy**

In [ ]:
import numpy as np
np.arange(1,6)

array([1, 2, 3, 4, 5])

**Arange(n,m,k) method with step length
======>>>here n is the start value and m is the end value and k is the step length**

In [ ]:
import numpy as np
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

**using "linspace(n,m,k)" method to generate k linear spaced numbers in between n and m**

In [ ]:
import numpy as np
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

**using "reshape" method to reshaping the no of rows of rows and colums of a array**


In [ ]:
import numpy as np 
a=np.array([[1,2],[4,5],[7,9]])
print(a.shape)
print(a.reshape(2,3))
print()
print()
print(a.reshape(6,1))
print()
print()
print(a.reshape(1,6))

(3, 2)
[[1 2 4]
 [5 7 9]]


[[1]
 [2]
 [4]
 [5]
 [7]
 [9]]


[[1 2 4 5 7 9]]


**using "ravel()" method to flatten a arra========>>>>>>>> here ravel and all the above functions don't changes the original array it creates an another array **


In [ ]:
import numpy as np 
a=np.array([[1,2],[4,5],[7,9]])
print(a.ravel())
print()
print(a)            # here original array will be printed

[1 2 4 5 7 9]

[[1 2]
 [4 5]
 [7 9]]


**"min()" method gives the min value element and "max()" method will return the max value element and "sum()" method will sum all elements of the array**

In [ ]:
import numpy as np 
a=np.array([[1,2],[4,5],[7,9]])
print("The min value element of the given array is:",a.min())
print("The max value element of the given array is:",a.max())
print("The sum of all the eleents is:",a.sum())

The min value element of the given array is: 1
The max value element of the given array is: 9
The sum of all the eleents is: 28


**axis 0 is used to denote the columns and axis 1 is used to denote the rows         ===========>>>>>>>>>>>>>>>> To get the sum of the elements of a array column-wise we use axis = 0 and for row-wise axis = 1**

In [ ]:
import numpy as np 
a=np.array([[1,2],[4,5],[7,9]])
print(a)
print("column-wise sum:",a.sum(axis=0))
print()
print("Row-wise sum:",a.sum(axis=1))

[[1 2]
 [4 5]
 [7 9]]
column-wise sum: [12 16]

Row-wise sum: [ 3  9 16]


**using "sqrt()" method to get the square root of all elements of a array**

In [ ]:
import numpy as np 
a=np.array([[1,2],[4,5],[7,9]])
print(a)
print("Square root of the array is:")
np.sqrt(a)

[[1 2]
 [4 5]
 [7 9]]
Square root of the array is:


array([[1.        , 1.41421356],
       [2.        , 2.23606798],
       [2.64575131, 3.        ]])

**using "std()" method to get the standard deviation for the given matrix**

In [ ]:
import numpy as np 
a=np.array([[1,2],[4,5],[7,9]])
np.std(a)

2.748737083745107

**using "array1.dot(array2)" to get the matrix product of two arrays**

In [ ]:
import numpy as np 
a=np.array([[1,2],[3,4]])
b=np.array([[7,8],[9,10]])
print(a)
print(b)
print("matrix product of matrix a and matrix b is:")
print(a.dot(b))
print("matrix product of b and a is:")
print(b.dot(a))

[[1 2]
 [3 4]]
[[ 7  8]
 [ 9 10]]
matrix product of matrix a and matrix b is:
[[25 28]
 [57 64]]
matrix product of b and a is:
[[31 46]
 [39 58]]
